version: 2

jobs:
    build:
        working_directory: ~/benchmark
        docker:
            - image: lightjason/benchmark:latest

        branches:
            ignore:
                - master
                - /dev-.*/

        environment:
            TZ: "/usr/share/zoneinfo/Europe/Berlin"
            JAVA_OPTS: "-XX:+AggressiveOpts -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:CMSInitiatingOccupancyFraction=45 -Xmx3686M"

        steps:
            - checkout
            - run: 
                name: Git Clean
                command: git clean -xdf && git fetch -p && git gc --prune=now
            - run:
                name: Execute Scenario
                command: benchmark synchronizedcount5.yml
            - store_artifacts:    
                path: synchronizedcount5.yml    
            - store_artifacts:
                path: *.json
            - store_artifacts:    
                path: *.asl
            - run:
                name: Github Release
                command: |
                    if [ ! -z "$GITHUBTOKEN" ]; then
                        mkdir /tmp/scenario
                        cp synchronizedcount5.yml /tmp/scenario
                        cp *.asl /tmp/scenario
                        cp *.json /tmp/scenario
                        export TAG=$((CIRCLE_BUILD_NUM / 1000)).$((CIRCLE_BUILD_NUM / 100 % 10)).$((CIRCLE_BUILD_NUM % 100))
                        ghr -t $GITHUBTOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -c $CIRCLE_SHA1 -b "$(git log -1 $CIRCLE_SHA1 --pretty=format:%s)" $CIRCLE_BRANCH-v$TAG /tmp/scenario
                    fi    
   