version: 2

jobs:
    build:
        working_directory: ~/benchmark
        docker:
            - image: lightjason/benchmark:latest

        branches:
            ignore:
                - master
                - /dev-.*/

        environment:
            TZ: "/usr/share/zoneinfo/Europe/Berlin"
            JAVA_OPTS: "-XX:+UseConcMarkSweepGC -Xmx3584M"

        steps:
            - checkout
            - run: 
                name: Git Clean
                command: git clean -xdf && git fetch -p && git gc --prune=now
            - run:
                name: Execute Scenario
                command: |
                    export JAVA_OPTS="$JAVA_OPTS -Djava.util.concurrent.ForkJoinPool.common.parallelism=$((nproc - 1)"
                    echo $JAVA_OPTS
                    benchmark synchronizedcount5.yml
            - store_artifacts:
                path: synchronizedcount5.json
            - run:
                name: Github Release
                command: |
                    if [ ! -z "$GITHUBTOKEN" ]; then
                        export TAG=$((CIRCLE_BUILD_NUM / 1000)).$((CIRCLE_BUILD_NUM / 100 % 10)).$((CIRCLE_BUILD_NUM % 100))
                        ghr -t $GITHUBTOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -c $CIRCLE_SHA1 -b "$(git log -1 $CIRCLE_SHA1 --pretty=format:%s)" $CIRCLE_BRANCH-v$TAG synchronizedcount5.json
                    fi    
   